### PR TITLE
echo ar is bad

### PR DESCRIPTION
**Pull request by ericzhu105**
echo ar sucks

### CODE REVIEW

**Comment by LoboAdrian** [comment]
Eric,  make something serious, that would actually contribute, then I'll help you with hacktoberfest

**Comment by Muirrum** [comment]
@LoboAdrian mark this as invalid so Eric has to actually try

**Comment by LoboAdrian** [comment]
yeah, i'm not approving it

**Comment by LoboAdrian** [comment]
alright, i'm closing this

**Pull request closed without merging**
